services:
  app:
    build: .
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - projectnetwork
    command: >
      sh -c "chmod +x ./scripts/initial-setup.sh &&
      ./scripts/initial-setup.sh"
  
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projectnetwork

  redis:
    image: redis:8
    networks:
      - projectnetwork
  
  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./scripts/generate-dev-certs.sh:/scripts/generate-dev-certs.sh
      - static_volume:/var/www/static
    depends_on:
      - app
    networks:
      - projectnetwork
    command: sh -c "sleep 15 && chmod +x /scripts/generate-dev-certs.sh && /scripts/generate-dev-certs.sh && nginx -g 'daemon off;'"

volumes:
  postgres_data:
  static_volume:

networks:
  projectnetwork:
    driver: bridge
    